#!/usr/bin/env python
# -*- coding: utf-8 -*-

STATUS_CODE_OK                           = {'id': 0   , 'msg': 'OK'}
STATUS_CODE_ERR_CMD_NOT_FOUND            = {'id': 200001, 'msg': 'CMD NOT FOUND ERROR'}
STATUS_CODE_ERR_DATA_FIELD               = {'id': 200002, 'msg': 'DATA FIELD ERROR'}
STATUS_CODE_ERR_CMD_IMP                  = {'id': 200003, 'msg': 'CMD IMPLEMENT ERROR'}
STATUS_CODE_ERR_USER_NOT_EXIST           = {'id': 200004, 'msg': 'USER DOES NOT EXIST'}
STATUS_CODE_ERR_TOKEN_EXPIRED            = {'id': 200005, 'msg': 'TOKEN EXPIRED'}
STATUS_CODE_ERR_SIGNATURE                = {'id': 200006, 'msg': 'SIGNATURE ERROR'}
STATUS_CODE_ERR_JSON_FORMAT              = {'id': 200007, 'msg': 'JSON DATA FORMAT ERROR'}
STATUS_CODE_ERR_SET_SESSION              = {'id': 200008, 'msg': 'ERROR SETTING SESSION'}
STATUS_CODE_ERR_SET_SHARD_INFO           = {'id': 200009, 'msg': 'ERROR SETTING SHARD INFO'}
STATUS_CODE_ERR_USER_HAD_BEEN_SUSPENDED  = {'id': 200010, 'msg': 'SUSPENDED ACCOUNT'}
STATUS_CODE_ERR_EXCEPTION                = {'id': 209999, 'msg': 'EXCEPTION ERROR'}

# Main Game
STATUS_CODE_ERR_ANOTHER_DEVICE_IS_PLAYING         = {'id': 200020, 'msg': 'ANOTHER DEVICE IS PLAYING NOW'}
STATUS_CODE_ERR_COIN_NOT_ENOUGH                   = {'id': 200021, 'msg': 'HAVE NOT ENOUGH COIN'}
# STATUS_CODE_ERR_LEVEL_AND_BET_NOT_ENOUGH        = {'id': 200022, 'msg': 'HAVE NOT ENOUGH LEVEL AND BET'}
# STATUS_CODE_ERR_LEVEL_NOT_ENOUGH_IN_HRC         = {'id': 200023, 'msg': 'LEVEL NOT ENOUGH TO PLAY HIGH ROLLER CENTER'}
STATUS_CODE_ERR_SPIN_AUTH                         = {'id': 200024, 'msg': 'SPIN AUTHENTICATION FAILED'}
STATUS_CODE_ERR_GAME_SESSION_MISSING              = {'id': 200025, 'msg': 'GAME SESSION MISSING'}
STATUS_CODE_ERR_BET_ALREADY_CONSUMED              = {'id': 200026, 'msg': 'BET HAD ALREADY BEEN CONSUMED'}
STATUS_CODE_ERR_BET_DATA_NOT_EXISTS               = {'id': 200027, 'msg': 'BET DATA NOT EXISTS'}
STATUS_CODE_ERR_USER_IS_PLAYING_SOCKET_GAME       = {'id': 200028, 'msg': 'USER IS PLAYING SOCKET GAME NOW'}
STATUS_CODE_ERR_MAINGAME_STATE_EXCEPTION          = {'id': 200029, 'msg': 'MAINGAME STATE ERROR'}
STATUS_CODE_ERR_BONUSGAME_STATE_EXCEPTION         = {'id': 200030, 'msg': 'BONUSGAME STATE ERROR'}
STATUS_CODE_ERR_FEVERGAME_STATE_EXCEPTION         = {'id': 200031, 'msg': 'FEVERGAME STATE ERROR'}
STATUS_CODE_ERR_GAME_IS_UNDER_CONSTRUCTION        = {'id': 200032, 'msg': 'GAME IS UNDER CONSTRUCTION'}
STATUS_CODE_ERR_GET_GAME_STATE_ERROR              = {'id': 200033, 'msg': 'GET GAME STATE ERROR'}
STATUS_CODE_ERR_UPDATE_GAME_STATE_ERROR           = {'id': 200034, 'msg': 'UPDATE GAME STATE ERROR'}
STATUS_CODE_ERR_USER_BALANCE_ERROR                = {'id': 200035, 'msg': 'USER BALANCE ERROR'}
STATUS_CODE_ERR_USER_START_GAME_INFO_SN_ERROR     = {'id': 200036, 'msg': 'USER USER START GAME INFO SN ERROR'}
STATUS_CODE_ERR_DOUBLEGAME_STATE_EXCEPTION        = {'id': 200037, 'msg': 'DOUBLEGAME STATE ERROR'}
STATUS_CODE_ERR_DOUBLEGAME_IS_UNDER_CONSTRUCTION  = {'id': 200038, 'msg': 'DOUBLEGAME IS UNDER CONSTRUCTION'}
STATUS_CODE_ERR_DOUBLEGAME_LAST_WIN_DATA_ERROR    = {'id': 200039, 'msg': 'DOUBLEGAME LAST WIN ERROR'}
STATUS_CODE_ERR_DOUBLEGAME_STATE_ILLEGAL_ERROR    = {'id': 200040, 'msg': 'DOUBLEGAME STATE ILLEGAL ERROR'}
STATUS_CODE_ERR_EXTRABET_NOT_SUPPORT              = {'id': 200042, 'msg': 'THIS GAME HAS NOT SUPPORT EXTRA BET'}

# API Server Connect
STATUS_CODE_ERR_API_SIGN_ERROR                    = {'id': 201001, 'msg': 'API SIGN ERROR'}
STATUS_CODE_ERR_API_CMD_DATA_ILLEAGL              = {'id': 201002, 'msg': 'API CMD DATA ILLEAGL'}
STATUS_CODE_ERR_API_USER_NOT_EXIST                = {'id': 201003, 'msg': 'API USER NOT EXIST'}
STATUS_CODE_ERR_API_CMD_DUPLICATE                 = {'id': 201005, 'msg': 'API CMD DUPLICATE'}
STATUS_CODE_ERR_API_USER_BALANCE_NOT_EXIST        = {'id': 201009, 'msg': 'API USER BALANCE NOT EXIST'}
STATUS_CODE_ERR_API_COIN_NOT_ENOUGH               = {'id': 201011, 'msg': 'API COIN NOT ENOUGH'}
STATUS_CODE_ERR_API_USER_DATA_NOT_EXIST           = {'id': 201013, 'msg': 'API USER DATA NOT EXIST'}
STATUS_CODE_ERR_API_DATABASE_ERROR                = {'id': 201099, 'msg': 'API DATABASE ERROR'}
STATUS_CODE_ERR_API_SERVER_UNKNOWN_ERROR          = {'id': 201998, 'msg': 'API SERVER UNKNOWN ERROR'}
STATUS_CODE_ERR_API_SERVER_ERROR                  = {'id': 201999, 'msg': 'API SERVER ERROR'}

# Login
STATUS_CODE_ERR_API_VERIFY_ERROR                  = {'id': 202001, 'msg': 'API VERIFY ERROR'}
STATUS_CODE_ERR_GAME_ID_INCONSISTENT              = {'id': 202002, 'msg': 'GAME ID INCONSISTENT'}
STATUS_CODE_ERR_API_ADD_COIN_FAIL                 = {'id': 202101, 'msg': 'API ADD COIN FAIL'}

# Bag System
STATUS_CODE_ERR_ALREADY_IN_FREE_GAME              = {'id': 203001, 'msg': 'ALREADY IN FREE GAME'}
STATUS_CODE_ERR_USE_ITEM_FAILED                   = {'id': 203002, 'msg': 'USE ITEM FAILED'}

#
STATUS_CODE_ERR_ROOM_NOT_AVAILABLE_TO_ENTER       = {'id': 200041, 'msg': 'ROOM IS NOT AVAILABLE TO ENTER'} #房間不可進入
STATUS_CODE_ERR_ROOM_IS_FULL                      = {'id': 200042, 'msg': 'ROOM IS FULL'}    #房間已滿
STATUS_CODE_ERR_WAITING_FOR_NEW_ROUND             = {'id': 200043, 'msg': 'WAITING FOR NEW ROUND'}    #遊戲開獎中
STATUS_CODE_ERR_PLAYER_ROUND                      = {'id': 200044, 'msg': 'PLAYER ROUND ERROR'}


# Social Network
# STATUS_CODE_ERR_MAX_FRND_EXCEEDED        = {'id': 200100  , 'msg': 'EXCEED MAXIMUM NUMBER OF FRIENDS '}
# STATUS_CODE_ERR_OTHER_MAX_FRND_EXCEEDED  = {'id': 200101  , 'msg': 'THE OTHER SIDE EXCEED MAXIMUM NUMBER OF FRIENDS '}
# STATUS_CODE_ERR_TWO_ID_NOT_MATCH         = {'id': 200102  , 'msg': 'FRIEND CODE AND FACEBOOK ID ARE NOT THE SAME USER'}
# STATUS_CODE_ERR_3RD_PARTY_ID_NOT_EXIST   = {'id': 200103  , 'msg': 'THIRD-PARTY ID DOES NOT EXIST'}
# STATUS_CODE_ERR_FRND_ALREADY_EXIST       = {'id': 200104  , 'msg': 'HAS BECOME FRIEND'}
# STATUS_CODE_ERR_3RD_PARTY_ID_BEEN_DELETED= {'id': 200105  , 'msg': 'THE THIRD-PARTY HAS BEEN DELETE BY YOU OR YOUR FRIEND, PLEASE ADD FRIEND BY USING FRIEND CODE'}
# STATUS_CODE_ERR_INVITATION_HAS_BEEN_SENT = {'id': 200106  , 'msg': 'THE INVITATION HAS BEEN SENT'}
# STATUS_CODE_ERR_NO_FRND_TO_ACCEPT        = {'id': 200107  , 'msg': 'THERE IS NO FRIEND TO ACCEPT'}
# STATUS_CODE_ERR_ADD_YOURSELF_FRND        = {'id': 200108  , 'msg': 'CAN NOT ADD YOURSELF AS A FRIEND'}
# STATUS_CODE_ERR_NOT_UP_TO_LEVEL          = {'id': 200109  , 'msg': 'THE LEVEL IS NOT UP TO STANDARD'}
# STATUS_CODE_ERR_INVITE_CODE_FILLED       = {'id': 200110  , 'msg': 'THE INVITE CODE HAS BEEN FILLED'}
# STATUS_CODE_ERR_GET_REWARD_FAIL          = {'id': 200111  , 'msg': 'THE REWARD ID NOT EXIST OR CAN NOT RECEIVE'}
# STATUS_CODE_ERR_REWARD_HAS_BEEN_RECEIVED = {'id': 200112  , 'msg': 'THE REWARD HAS BEEN RECEIVED'}
# STATUS_CODE_ERR_COUPON_NOT_ACCESSIBLE    = {'id': 200113  , 'msg': 'THE COUPON IS NOT ACCESSIBLE'}
# STATUS_CODE_ERR_COUPON_NOT_EXIST         = {'id': 200114  , 'msg': 'THE COUPON IS NOT EXIST'}
# STATUS_CODE_ERR_COUPON_HAS_BEEN_RECEIVED = {'id': 200115  , 'msg': 'THE COUPON HAS BEEN RECEIVED'}
# STATUS_CODE_ERR_COUPON_TYPE_NOT_EXIST    = {'id': 200116  , 'msg': 'THE TYPE OF COUPON IS NOT EXIST, PLEASE CHECK COUPON INFO RULE IN CONST.PY'}
# STATUS_CODE_ERR_RELATIONSHIP_NOT_EXIST   = {'id': 200117  , 'msg': 'THE RELATIONSHIP BETWEEN USER AND FRIEND IS NOT EXIST'}


# # Special Bonus
# STATUS_CODE_ERR_USER_BONUS_INFO          = {'id': 200  , 'msg': 'SPECIAL BONUS DATA ERROR'}
# STATUS_CODE_ERR_SB_STATE                 = {'id': 201  , 'msg': 'SPECIAL BONUS STATE ERROR'}
# STATUS_CODE_ERR_SB_GAME_RATE             = {'id': 202  , 'msg': 'SPECIAL BONUS GAME RATE TABLE ERROR'}
#
# # MsteryStore
# STATUS_CODE_ERR_MYSTERY_REFRESH_COST_NOT_RIGHT      = {'id': 251  , 'msg': 'MYSTERY REFRESH COST NOT RIGHT'}
# STATUS_CODE_ERR_MYSTERY_REFRESH_TIMES_NOT_ENOUGH    = {'id': 252  , 'msg': 'MYSTERY REFRESH TIMES NOT ENOUGH'}
# STATUS_CODE_ERR_MYSTERY_PRODUCT_NOT_FOUND           = {'id': 253  , 'msg': 'MYSTERY PRODUCT NOT FOUND'}
# STATUS_CODE_ERR_MYSTERY_PRODUCT_SOLD_OUT            = {'id': 254  , 'msg': 'MYSTERY PRODUCT SOLD OUT'}
# STATUS_CODE_ERR_MYSTERY_CURRENCY_TYPE_ERROR         = {'id': 255  , 'msg': 'MYSTERY CURRENCY TYPE ERROR'}
# STATUS_CODE_ERR_MYSTERY_PRODUCT_EXPIRE              = {'id': 256  , 'msg': 'MYSTERY PRODUCT EXPIRE'}
# STATUS_CODE_ERR_MYSTERY_PRODUCT_GET_ALREADY         = {'id': 257  , 'msg': 'MYSTERY PRODUCT GET ALREADY'}
# STATUS_CODE_ERR_MYSTERY_USER_BALANCE_NOT_ENOUGH     = {'id': 258  , 'msg': 'MYSTERY USER BALANCE NOT ENOUGH'}
#
# # Pay System
# STATUS_CODE_ERR_ILLEGAL_PAY_DATA          = {'id': 300 , 'msg': 'PAY DATA IS ILLEGAL'}
# STATUS_CODE_ERR_INVALID_PURCHASE_ID       = {'id': 301 , 'msg': 'PURCHASE ID IS INVALID'}
# STATUS_CODE_ERR_THIRD_PARTY_VERIFY_FAIL   = {'id': 302 , 'msg': 'THIRD PARTY VERIFY FAIL'}
# STATUS_CODE_ERR_ILLEGAL_FLASH_SALE_ID     = {'id': 303 , 'msg': 'FLASH SALE ID IS ILLEGAL'}
# STATUS_CODE_ERR_WEB_PAY_MAKE_ORDER_FAIL   = {'id': 304 , 'msg': 'WEB PAY MAKE ORDER FAIL'}
# STATUS_CODE_ERR_USER_ORDER_NOT_EXIST      = {'id': 305 , 'msg': 'USER ORDER NOT EXIST'}
#
# #NCube connection
# STATUS_CODE_NCUBE_CONNECTION_ERROR        = {'id': 400 , 'msg': 'NCUBE CONNECT ERROR'}
# STATUS_CODE_NCUBE_INVOKE_SERVICE_ERROR    = {'id': 401 , 'msg': 'NCUBE INVOKE SERVICE ERROR'}
# STATUS_CODE_NCUBE_DATA_PARSE_ERROR        = {'id': 402 , 'msg': 'NCUBE DATA PARSE ERROR'}
#
# # Rank System
# STATUS_CODE_ERR_RANK_EVENT_NOT_FOUND      = {'id': 500  , 'msg': 'CAN NOT FIND THE RANK EVENT ACCORDING WITH THE CONDITIONS'}
#
# # Achievement
# STATUS_CODE_ERR_REWARD_CANNOT_RECEIVED    = {'id': 600  , 'msg': 'THE REWARD HAS BEEN RECEIVED OR LEVEL IS NOT UP TO STANDARD'}
# STATUS_CODE_ERR_ACHI_DATA_AUTH_FAIL       = {'id': 601  , 'msg': 'THE ACHIEVEMENT DATA IS INVALID'}
#
# # Daily Bonus New
# STATUS_CODE_ERR_DISABLE_TO_PLAY_DAILY_SICBO = {'id': 700 , 'msg': 'DISABLE TO PLAY DAILY SICBO'}
#
# # Arena
# STATUS_CODE_ERR_ARENA_COLLECT_AWARD_FAILED        = {'id': 710  , 'msg': 'COLLECT ARENA AWARD FAILED'} #撿獎勵失敗
# STATUS_CODE_ERR_ARENA_ROOM_HISTORY_IS_EXPIRED     = {'id': 711  , 'msg': 'ROOM HISTORY IS EXPIRED'} #房間已經過期不可查閱

# STATUS_CODE_ERR_USER_PAY_FEE_FAILED               = {'id': 714  , 'msg': 'USER PAY FEE FAILED'} #玩家付門票失敗
# STATUS_CODE_ERR_USER_ARENA_GAME_TIMES_UP          = {'id': 715  , 'msg': 'USER ARENA GAME TIMES UP'} #玩家的競賽館時限已到
# STATUS_CODE_ERR_USER_ARENA_GAME_IS_OVER           = {'id': 716  , 'msg': 'USER ARENA GAME IS OVER'} #玩家的競賽館balance已花光
# STATUS_CODE_ERR_ARENA_GAME_STATE_EXCEPTION        = {'id': 717  , 'msg': 'ARENA MAINGAME STATE ERROR'} #maingame流程有誤
# STATUS_CODE_ERR_ARENA_BONUSGAME_STATE_EXCEPTION   = {'id': 718  , 'msg': 'ARENA BONUSGAME STATE ERROR'} #bonusgame流程有誤
# STATUS_CODE_ERR_ARENA_FEVERGAME_STATE_EXCEPTION   = {'id': 719  , 'msg': 'ARENA FEVERGAME STATE ERROR'} #devergame流程有誤
# STATUS_CODE_ERR_ARENA_GAME_NOT_FINISHED           = {'id': 720  , 'msg': 'ARENA GAME IS NOT FINISHED'} #玩家遊戲尚未結束
# STATUS_CODE_ERR_ARENA_GAME_IS_FINISHED            = {'id': 721  , 'msg': 'ARENA GAME IS FINISHED'} #玩家遊戲已結束
# STATUS_CODE_ERR_ARENA_FREE_PASS_NOT_NOUGH         = {'id': 722  , 'msg': 'ARENA FREE PASS NOT NOUGH'} #FREEPASS 不夠
# STATUS_CODE_ERR_ARENA_FREE_PASS_NOT_AVAILABLE     = {'id': 723  , 'msg': 'ARENA FREE PASS NOT AVAILABLE'} #FREEPASS 不可使用於此房
#
#
# # PK Tournament
# STATUS_CODE_ERR_PK_BEGIN_ROUND_ERR        = {'id': 800  , 'msg': 'PK BEGIN ROUND ERROR'}
# STATUS_CODE_ERR_PK_ROOM_ID_ERR            = {'id': 801  , 'msg': 'PK ROOM ID ERROR'}
# STATUS_CODE_ERR_PK_PKTICKET_NOT_ENOUGH    = {'id': 802  , 'msg': 'PK PK TICKET NOT ENOUGH'}
# STATUS_CODE_ERR_PK_JOIN_ROUND_DATA_ERR    = {'id': 803  , 'msg': 'PK JOIN ROUND DATA ERROR'} #資料不合，需重新ask_join_round
# STATUS_CODE_ERR_PK_CREATE_ROUND_ERR       = {'id': 804  , 'msg': 'PK CREATE ROUND ERROR'} #不明原因，新增比賽失敗
# STATUS_CODE_ERR_PK_BATTLE_ID_ERR          = {'id': 805  , 'msg': 'PK BATTLE ID ERROR'} #找不到比賽
# STATUS_CODE_ERR_PK_GET_RESULT_STATUS_ERR  = {'id': 806  , 'msg': 'PK GET RESULT STATUS ERROR'} #玩家比賽還在進行中
# STATUS_CODE_ERR_PK_STATUS_ERR             = {'id': 807  , 'msg': 'PK GET STATUS ERROR'} #玩家狀態錯誤，無法retry、play again、next round
# STATUS_CODE_ERR_PK_BATTLE_NOT_BEGIN       = {'id': 808  , 'msg': 'PK BATTLE NOT BEGIN'} #遊玩時，回傳比賽還未開始
# STATUS_CODE_ERR_PK_BATTLE_FINISH          = {'id': 809  , 'msg': 'PK BATTLE FINISH'} #遊玩時，回傳比賽已經結束
# STATUS_CODE_ERR_PK_GAME_ID_ERR            = {'id': 810  , 'msg': 'PK GAME ID ERROR'} #遊玩時，遊戲id錯誤
# STATUS_CODE_ERR_PK_BET_VALUE_ERR          = {'id': 811  , 'msg': 'PK BET VALUE ERROR'} #遊玩時，押注值錯誤
# STATUS_CODE_ERR_MAX_BATTLE_COUNT          = {'id': 812  , 'msg': 'PK MAX BATTLE COUNT'} #已達玩家比賽數量上限
# STATUS_CODE_ERR_PK_VERSION_ERROR          = {'id': 813  , 'msg': 'PK VERSION ERROR'} #client版號太低，無法進入
# STATUS_CODE_ERR_PK_FREE_PASS_NOT_ENOUGH   = {'id': 814  , 'msg': 'PK FREEPASS NOT ENOUGH'} #FreePass 不足
# STATUS_CODE_ERR_PK_IN_MAINTENANCE_STATUS  = {'id': 815  , 'msg': 'PK IN MAINTENANCE STATUS'} #魚機PK server維修中
# STATUS_CODE_ERR_PK_ADD_EXPIRATION         = {'id': 816  , 'msg': 'PK ADD EXPIRATION'} #魚機PK server維修中, 延長retry/retryed時間
#
# # Game Center
# STATUS_CODE_ERR_GEM_NOT_ENOUGH                 = {'id': 900, 'msg': 'HAVE NOT ENOUGH GEM'}
# STATUS_CODE_ERR_THIS_GAME_NO_DOUBLE_UP         = {'id': 901, 'msg': 'THIS GAME HAS NO DOUBLE UP'}
# STATUS_CODE_ERR_WONDERLAND_CHANCE_NOT_MATCH    = {'id': 910, 'msg': 'CHANCE OF WONDERLAND IS NOT MATCH'}
# STATUS_CODE_ERR_WONDERLAND_BET_NOT_MATCH       = {'id': 911, 'msg': 'BET OF WONDERLAND IS NOT MATCH'}
#
# # Scratch lottery
# STATUS_CODE_ERR_SL_NOT_ENABLE              = {'id': 950, 'msg': 'SL NOT ENABLE'}
# STATUS_CODE_ERR_SL_CARD_NOT_EXIST          = {'id': 951, 'msg': 'SL CRAD NOT EXIST'}
# STATUS_CODE_ERR_SL_PAY_FAILED              = {'id': 952, 'msg': 'SL PAY FAILED'}
# STATUS_CODE_ERR_SL_FREE_CARD_NOT_AVAILABLE = {'id': 953, 'msg': 'SL FREE CARD NOT AVAILABLE'}
# STATUS_CODE_ERR_SL_FREE_CARD_GET_ALREADY   = {'id': 954, 'msg': 'SL FREE CARD GET ALREADY'}

