#!/usr/bin/env python
# -*- coding: utf-8 -*-

STATUS_CODE_OK                           = {'id': 0   , 'msg': 'OK'}
STATUS_CODE_ERR_CMD_NOT_FOUND            = {'id': -200001, 'msg': 'CMD NOT FOUND ERROR'}
STATUS_CODE_ERR_DATA_FIELD               = {'id': -200002, 'msg': 'DATA FIELD ERROR'}
STATUS_CODE_ERR_CMD_IMP                  = {'id': -200003, 'msg': 'CMD IMPLEMENT ERROR'}
STATUS_CODE_ERR_USER_NOT_EXIST           = {'id': -200004, 'msg': 'USER DOES NOT EXIST'}
STATUS_CODE_ERR_TOKEN_EXPIRED            = {'id': -200005, 'msg': 'TOKEN EXPIRED'}
STATUS_CODE_ERR_SIGNATURE                = {'id': -200006, 'msg': 'SIGNATURE ERROR'}
STATUS_CODE_ERR_JSON_FORMAT              = {'id': -200007, 'msg': 'JSON DATA FORMAT ERROR'}
STATUS_CODE_ERR_SET_SESSION              = {'id': -200008, 'msg': 'ERROR SETTING SESSION'}
STATUS_CODE_ERR_SET_SHARD_INFO           = {'id': -200009, 'msg': 'ERROR SETTING SHARD INFO'}
STATUS_CODE_ERR_USER_HAD_BEEN_SUSPENDED  = {'id': -200010, 'msg': 'SUSPENDED ACCOUNT'}
STATUS_CODE_ERR_EXCEPTION                = {'id': -209999, 'msg': 'EXCEPTION ERROR'}

# Slot Game
STATUS_CODE_ERR_ANOTHER_DEVICE_IS_PLAYING         = {'id': -200020, 'msg': 'ANOTHER DEVICE IS PLAYING NOW'}
STATUS_CODE_ERR_COIN_NOT_ENOUGH                   = {'id': -200021, 'msg': 'HAVE NOT ENOUGH COIN'}
# STATUS_CODE_ERR_LEVEL_AND_BET_NOT_ENOUGH        = {'id': -200022, 'msg': 'HAVE NOT ENOUGH LEVEL AND BET'}
# STATUS_CODE_ERR_LEVEL_NOT_ENOUGH_IN_HRC         = {'id': -200023, 'msg': 'LEVEL NOT ENOUGH TO PLAY HIGH ROLLER CENTER'}
STATUS_CODE_ERR_SPIN_AUTH                         = {'id': -200024, 'msg': 'SPIN AUTHENTICATION FAILED'}
STATUS_CODE_ERR_GAME_SESSION_MISSING              = {'id': -200025, 'msg': 'GAME SESSION MISSING'}
STATUS_CODE_ERR_BET_ALREADY_CONSUMED              = {'id': -200026, 'msg': 'BET HAD ALREADY BEEN CONSUMED'}
STATUS_CODE_ERR_BET_DATA_NOT_EXISTS               = {'id': -200027, 'msg': 'BET DATA NOT EXISTS'}
STATUS_CODE_ERR_USER_IS_PLAYING_SOCKET_GAME       = {'id': -200028, 'msg': 'USER IS PLAYING SOCKET GAME NOW'}
STATUS_CODE_ERR_MAINGAME_STATE_EXCEPTION          = {'id': -200029, 'msg': 'MAINGAME STATE ERROR'}
STATUS_CODE_ERR_BONUSGAME_STATE_EXCEPTION         = {'id': -200030, 'msg': 'BONUSGAME STATE ERROR'}
STATUS_CODE_ERR_FEVERGAME_STATE_EXCEPTION         = {'id': -200031, 'msg': 'FEVERGAME STATE ERROR'}
STATUS_CODE_ERR_GAME_IS_UNDER_CONSTRUCTION        = {'id': -200032, 'msg': 'GAME IS UNDER CONSTRUCTION'}
STATUS_CODE_ERR_GET_GAME_STATE_ERROR              = {'id': -200033, 'msg': 'GET GAME STATE ERROR'}
STATUS_CODE_ERR_UPDATE_GAME_STATE_ERROR           = {'id': -200034, 'msg': 'UPDATE GAME STATE ERROR'}
STATUS_CODE_ERR_USER_BALANCE_ERROR                = {'id': -200035, 'msg': 'USER BALANCE ERROR'}
STATUS_CODE_ERR_USER_START_GAME_INFO_SN_ERROR     = {'id': -200036, 'msg': 'USER USER START GAME INFO SN ERROR'}
STATUS_CODE_ERR_DOUBLEGAME_STATE_EXCEPTION        = {'id': -200037, 'msg': 'DOUBLEGAME STATE ERROR'}
STATUS_CODE_ERR_DOUBLEGAME_IS_UNDER_CONSTRUCTION  = {'id': -200038, 'msg': 'DOUBLEGAME IS UNDER CONSTRUCTION'}
STATUS_CODE_ERR_DOUBLEGAME_LAST_WIN_DATA_ERROR    = {'id': -200039, 'msg': 'DOUBLEGAME LAST WIN ERROR'}
STATUS_CODE_ERR_DOUBLEGAME_STATE_ILLEGAL_ERROR    = {'id': -200040, 'msg': 'DOUBLEGAME STATE ILLEGAL ERROR'}
STATUS_CODE_ERR_OVER_MAX_COIN                     = {'id': -200041, 'msg': 'OVER MAX COIN'}
STATUS_CODE_ERR_EXTRABET_NOT_SUPPORT              = {'id': -200042, 'msg': 'THIS GAME HAS NOT SUPPORT EXTRA BET'}
STATUS_CODE_ERR_EXTRABET_STATE_NOT_EXIT           = {'id': -200043, 'msg': 'EXTRA BET STATE NOT EXIT'}
STATUS_CODE_ERR_UPDATE_RESULT_FAIL                = {'id': -200044, 'msg': 'UPDATE_RESULT_FAIL'}
STATUS_CODE_ERR_GAME_INFO_NOT_FOUND               = {'id': -200045, 'msg': 'GAME INFO NOT FOUND'}
STATUS_CODE_ERR_SPIN_RESULT_IS_NONE               = {'id': -200046, 'msg': 'SPIN_RESULT_IS_NONE'}

# API Server Connect
STATUS_CODE_ERR_API_SIGN_ERROR                    = {'id': -201001, 'msg': 'API SIGN ERROR'}
STATUS_CODE_ERR_API_CMD_DATA_ILLEAGL              = {'id': -201002, 'msg': 'API CMD DATA ILLEAGL'}
STATUS_CODE_ERR_API_USER_NOT_EXIST                = {'id': -201003, 'msg': 'API USER NOT EXIST'}
STATUS_CODE_ERR_API_CMD_DUPLICATE                 = {'id': -201005, 'msg': 'API CMD DUPLICATE'}
STATUS_CODE_ERR_API_USER_BALANCE_NOT_EXIST        = {'id': -201009, 'msg': 'API USER BALANCE NOT EXIST'}
STATUS_CODE_ERR_API_COIN_NOT_ENOUGH               = {'id': -201011, 'msg': 'API COIN NOT ENOUGH'}
STATUS_CODE_ERR_API_USER_DATA_NOT_EXIST           = {'id': -201013, 'msg': 'API USER DATA NOT EXIST'}
STATUS_CODE_ERR_API_VERIFY_ERROR                  = {'id': -201015, 'msg': 'API VERIFY ERROR'}
STATUS_CODE_ERR_API_DATABASE_ERROR                = {'id': -201099, 'msg': 'API DATABASE ERROR'}
STATUS_CODE_ERR_API_SERVER_UNKNOWN_ERROR          = {'id': -201998, 'msg': 'API SERVER UNKNOWN ERROR'}
STATUS_CODE_ERR_API_SERVER_ERROR                  = {'id': -201999, 'msg': 'API SERVER ERROR'}


STATUS_CODE_ERR_LOCAL_NO_LOBBY_DAO                = {'id': -202001, 'msg': 'LOCAL NO LOBBY DAO'}
STATUS_CODE_ERR_LOCAL_USER_BALANCE_ERROR          = {'id': -202001, 'msg': 'LOCAL USER BALANCE ERROR'}
